// Wish List
export const SET_WISH_LIST_ITEMS = "SET_WISH_LIST_ITEMS";
export const SET_WISH_LIST_IDS = "SET_WISH_LIST_IDS";
export const REMOVE_WISH_LIST_ITEM = "REMOVE_WISH_LIST_ITEM";
export const REMOVE_WISH_LIST_ID = "REMOVE_WISH_LIST_ID";
export const ADD_WISH_LIST_ITEM_TO_INDEX = "ADD_WISH_LIST_ITEM_TO_INDEX";
export const ADD_WISH_LIST_ID = "ADD_WISH_LIST_ID";
