<?php

namespace Ceres\Widgets\Helper\Factories\Settings;

/**
 * Class GenericSettingFactory
 *
 * This factory is used to create generic widget settings.
 * It just makes the generic methods `withType` and `withOptions` public visible.
 *
 * @package Ceres\Widgets\Helper\Factories\Settings
 */
class GenericSettingFactory extends BaseSettingFactory
{
    public function withType($type)
    {
        return parent::withType($type); // TODO: Change the autogenerated stub
    }

    public function withOption($key, $value)
    {
        return parent::withOption($key, $value); // TODO: Change the autogenerated stub
    }
}