on:
  push:
    branches:
      - "stable"
jobs:
  distribute_stable:
    runs-on: ubuntu-latest
    name: "Distribute changes on stable branch"
    steps:
      - uses: actions/checkout@v2
      - uses: alagos/regex-merge@v1.0
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          headBranch: "stable"
          branchRegex: '^.+\/stable\/.+$'
